#!/usr/bin/env python3
from pathlib import Path
import subprocess, sys
ROOT=Path(__file__).resolve().parents[1]

def run(name): subprocess.run([sys.executable,str(ROOT/'tools'/name)],check=True)

def main():
    run('verify_localization.py')
    run('verify_threat_db.py')
    run('autonomous_continuity_gate.py')
    run('cloud_intelligence_factory_3_5_gate.py')
    run('test_threat_intel_factory.py')
    run('web_protection_2_4_gate.py')
    run('zero_day_2_5_gate.py')
    run('android_kotlin_sanity_gate.py')
    run('android_api_compat_gate.py')
    run('android_string_format_gate.py')
    run('smart_ui_gate.py')
    run('production_validation_gate.py')
    run('release_hardening_gate.py')
    run('realtime_antivirus_gate.py')
    run('detection_strength_2_9_gate.py')
    run('lightweight_local_engine_3_0_gate.py')
    run('local_attack_prevention_3_1_gate.py')
    run('attack_detection_center_3_2_gate.py')
    run('android_api_compat_3_2_gate.py')
    run('data_exfiltration_guard_3_3_gate.py')
    run('play_protect_sideload_gate.py')
    run('direct_install_3_3_gate.py')
    run('core_runtime_3_4_gate.py')
    run('scan_findings_3_4_gate.py')
    run('threat_update_transparency_3_4_gate.py')
    run('manual_storage_scan_3_5_gate.py')
    run('message_scan_3_5_gate.py')
    run('background_activity_3_5_gate.py')
    run('play_release_3_5_gate.py')
    run('storage_scan_improvements_gate.py')
    run('web_shield_verification_3_4_gate.py')
    run('web_reputation_3_4_4_gate.py')
    run('protection_readiness_gate.py')
    manifest=(ROOT/'app/src/main/AndroidManifest.xml').read_text()
    if 'android.permission.WRITE_EXTERNAL_STORAGE' in manifest: raise SystemExit('PRIVACY_GATE_FAILED legacy_write_storage')
    if 'android:usesCleartextTraffic="false"' not in manifest or 'android.permission.INTERNET' not in manifest: raise SystemExit('PRIVACY_GATE_FAILED transport')
    if 'android.intent.action.PACKAGE_ADDED' not in manifest or 'android.intent.action.PACKAGE_REPLACED' not in manifest: raise SystemExit('REALTIME_PROTECTION_GATE_FAILED package_events')
    print('QUALITY_GATE_OK version=3.6.5 cloud_intelligence_factory=1 signed_cloud_updates=1 phone_raw_feeds=0 threat_update_actions=0 auto_build_push_main=1 manual_build=1 source_health=1 production_validation_infra=1 self_integrity=1 realtime_antivirus=1 downloads_protection=1 persistent_status=1 full_scan=1 manual_storage_scan=1 message_scan=1 background_activity_review=1 play_release=1 storage_scan_improvements=1 protection_readiness=1')
if __name__=='__main__': main()
